INSERT INTO DiaChi (maDiaChi, duong, quan, thanhPho, quocgia)
VALUES 
('DC0000', N'Đường Phạm Văn Chiêu', N'Quận Gò Vấp', N'Thành phố Hồ Chí Minh', N'Việt Nam'),
('DC0001', N'Đường Nguyễn Thái Sơn', N'Quận Thủ Đức', N'Thành phố Hồ Chí Minh', N'Việt Nam'),
('DC0002', N'Đường Cộng Hòa', N'Quận Tân Bình', N'Thành phố Hồ Chí Minh', N'Việt Nam'),
('DC0003', N'Đường Trường Chinh', N'Quận Bình Thạnh', N'Thành phố Hồ Chí Minh', N'Việt Nam'),
('DC0004', N'Đường Nguyễn Thái Học', N'Quận Phú Nhuận', N'Thành phố Hồ Chí Minh', N'Việt Nam'),
('DC0005', N'Đường 6', N'Quận Tân Phú', N'Thành phố Hồ Chí Minh', N'Việt Nam'),
('DC0006', N'Đường 7', N'Quận 1', N'Thành phố Hồ Chí Minh', N'Việt Nam'),
('DC0007', N'Đường 8', N'Quận 2', N'Thành phố Hồ Chí Minh', N'Việt Nam'),
('DC0008', N'Đường Hải Thượng Lãng Ông', N'Quận 3', N'Thành phố Hồ Chí Minh', N'Việt Nam'),
('DC0009', N'Đường 10', N'Quận 4', N'Thành phố Hồ Chí Minh', N'Việt Nam'),
('DC0010', N'Đường 11', N'Quận 5', N'Thành phố Hồ Chí Minh', N'Việt Nam'),
('DC0011', N'Đường 12', N'Quận 6', N'Thành phố Hồ Chí Minh', N'Việt Nam'),
('DC0012', N'Đường 13', N'Quận 7', N'Thành phố Hồ Chí Minh', N'Việt Nam'),
('DC0013', N'Đường 14', N'Quận 8', N'Thành phố Hồ Chí Minh', N'Việt Nam'),
('DC0014', N'Đường 15', N'Quận 9', N'Thành phố Hồ Chí Minh', N'Việt Nam'),
('DC0015', N'Đường 16', N'Quận 10', N'Thành phố Hồ Chí Minh', N'Việt Nam'),
('DC0016', N'Đường 17', N'Quận 11', N'Thành phố Hồ Chí Minh', N'Việt Nam'),
('DC0017', N'Đường 18', N'Quận 12', N'Thành phố Hồ Chí Minh', N'Việt Nam'),
('DC0018', N'Phố Bạch Mai', N'Quận Hai Bà Trưng', N'Thành phố Hà Nội', N'Việt Nam'),
('DC0019', N'Đường Tôn Đức Thắng', N'Quận Đống Đa', N'Thành phố Hà Nội', N'Việt Nam'),
('DC0020', N'Phố Hoàng Văn Thụ', N'Quận Ba Đình', N'Thành phố Hà Nội', N'Việt Nam'),
('DC0021', N'Đường Phạm Văn Đồng', N'Quận Cầu Giấy', N'Thành phố Hà Nội', N'Việt Nam'),
('DC0022', N'Đường Nguyễn Trãi', N'Quận Thanh Xuân', N'Thành phố Hà Nội', N'Việt Nam'),
('DC0023', N'Phố Láng', N'Quận Đống Đa', N'Thành phố Hà Nội', N'Việt Nam'),
('DC0024', N'Đường Lạc Long Quân', N'Quận Tây Hồ', N'Thành phố Hà Nội', N'Việt Nam'),
('DC0025', N'Phố Vũ Trọng Phụng', N'Quận Thanh Xuân', N'Thành phố Hà Nội', N'Việt Nam'),
('DC0026', N'Đường Hồ Tùng Mậu', N'Quận Cầu Giấy', N'Thành phố Hà Nội', N'Việt Nam'),
('DC0027', N'Phố Nguyễn Khánh Toàn', N'Quận Cầu Giấy', N'Thành phố Hà Nội', N'Việt Nam'),
('DC0028', N'Đường Trần Đại Nghĩa', N'Quận Hai Bà Trưng', N'Thành phố Hà Nội', N'Việt Nam'),
('DC0029', N'Phố Lê Văn Lương', N'Quận Thanh Xuân', N'Thành phố Hà Nội', N'Việt Nam'),
('DC0030', N'Đường Nguyễn Lương Bằng', N'Quận Đống Đa', N'Thành phố Hà Nội', N'Việt Nam'),
('DC0031', N'Phố Đặng Văn Ngữ', N'Quận Đống Đa', N'Thành phố Hà Nội', N'Việt Nam'),
('DC0032', N'Đường Thái Hà', N'Quận Đống Đa', N'Thành phố Hà Nội', N'Việt Nam'),
('DC0033', N'Phố Hào Nam', N'Quận Đống Đa', N'Thành phố Hà Nội', N'Việt Nam'),
('DC0035', N'Phan Đình Phùng', N'Hải Châu', N'Đà Nẵng', N'Việt Nam'),
('DC0036', N'Tôn Đức Thắng', N'Liên Chiểu', N'Đà Nẵng', N'Việt Nam'),
('DC0037', N'Hùng Vương', N'Hải Châu', N'Đà Nẵng', N'Việt Nam'),
('DC0038', N'Lê Duẩn', N'Hải Châu', N'Đà Nẵng', N'Việt Nam'),
('DC0039', N'Bạch Đằng', N'Hải Châu', N'Đà Nẵng', N'Việt Nam'),
('DC0040', N'Hà Huy Tập', N'Ngô Quyền', N'Hải Phòng', N'Việt Nam'),
('DC0041', N'Phạm Văn Đồng', N'Đằng Lâm', N'Hải An', N'Hải Phòng', N'Việt Nam'),
('DC0042', N'Lê Hồng Phong', N'Đằng Giang', N'Hải An', N'Hải Phòng', N'Việt Nam'),
('DC0043', N'Nguyễn Du', N'Hồng Bàng', N'Hải Phòng', N'Việt Nam'),
('DC0044', N'Tô Hiệu', N'Hồng Bàng', N'Hải Phòng', N'Việt Nam'),
('DC0045', N'Ngô Quyền', N'Lê Chân', N'Hải Phòng', N'Việt Nam'),
('DC0046', N'Phan Bội Châu', N'Đồng Hới', N'Quảng Bình', N'Việt Nam'),
('DC0047', N'Trường Chinh', N'Đồng Hới', N'Quảng Bình', N'Việt Nam'),
('DC0048', N'Lê Thánh Tông', N'Đồng Hới', N'Quảng Bình', N'Việt Nam'),
('DC0049', N'Tôn Đức Thắng', N'Tp. Huế', N'Thừa Thiên Huế', N'Việt Nam'),
('DC0050', N'Phan Đăng Lưu', N'Tp. Huế', N'Thừa Thiên Huế', N'Việt Nam'),
('DC0051', N'Trần Thái Tông', N'Tp. Huế', N'Thừa Thiên Huế', N'Việt Nam'),
('DC0052', N'Nguyễn Chí Thanh', N'Phường 10', N'Quận 5', N'Tp. Hồ Chí Minh', N'Việt Nam'),
('DC0053', N'Cống Quỳnh', N'Phường Nguyễn Cư Trinh', N'Quận 1', N'Tp. Hồ Chí Minh', N'Việt Nam'),
('DC0054', N'Phạm Ngũ Lão', N'Phường 2', N'Tp. Tây Ninh', N'Việt Nam'),
('DC0055', N'Lý Thường Kiệt', N'Phường 4', N'Tp. Tây Ninh', N'Việt Nam'),
('DC0056', N'Bình Minh', N'Phường 4', N'Tp. Tây Ninh', N'Việt Nam'),
('DC0057', N'Trần Quý Cáp', N'Phường 2', N'Tp. Tây Ninh', N'Việt Nam'),
('DC0058', N'Hùng Vương', N'Phường 2', N'Tp. Tây Ninh', N'Việt Nam'),
('DC0059', N'Đại lộ Bình Dương', N'Phường Phú Hòa', N'Tp. Thủ Dầu Một', N'Việt Nam'),
('DC0060', N'Lý Thái Tổ', N'Phường Phú Cường', N'Tp. Thủ Dầu Một', N'Việt Nam'),
('DC0061', N'Trần Hưng Đạo', N'Phường Hiệp An', N'Tp. Thủ Dầu Một', N'Việt Nam'),
('DC0062', N'Thủ Khoa Huân', N'Phường Phú Tân', N'Tp. Thủ Dầu Một', N'Việt Nam'),
('DC0063', N'Phạm Ngọc Thạch', N'Phường Chánh Nghĩa', N'Tp. Thủ Dầu Một', N'Việt Nam'),
('DC0064', N'Nguyễn An Ninh', N'Phường Quyết Thắng', N'Tp. Biên Hòa', N'Việt Nam'),
('DC0065', N'Quốc lộ 1A', N'Phường Tân Hiệp', N'Tp. Biên Hòa', N'Việt Nam'),
('DC0066', N'Bùi Thị Xuân', N'Phường Quang Vinh', N'Tp. Biên Hòa', N'Việt Nam'),
('DC0067', N'Nguyễn Thái Bình', N'Phường Tân Tiến', N'Tp. Biên Hòa', N'Việt Nam'),
('DC0068', N'Phạm Văn Thuận', N'Phường Bửu Long', N'Tp. Biên Hòa', N'Việt Nam')