/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import javax.swing.UIManager;

/**
 *
 * @author thanh
 */
public class GUI_QuanLiSanPham extends javax.swing.JFrame {

    /**
     * Creates new form GUI_QuanLiSanPham
     */
    public GUI_QuanLiSanPham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_top = new javax.swing.JPanel();
        pnl_filter = new javax.swing.JPanel();
        txt_filter = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pnl_advance = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        pnl_center = new javax.swing.JPanel();
        scr_table = new javax.swing.JScrollPane();
        tbl_dsnv = new javax.swing.JTable();
        pnl_bottom = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí sản phẩm");
        setName("frame_qlSanPham"); // NOI18N
        setSize(new java.awt.Dimension(1000, 700));

        pnl_top.setBackground(new java.awt.Color(153, 255, 153));
        pnl_top.setPreferredSize(new java.awt.Dimension(0, 100));
        pnl_top.setLayout(new javax.swing.BoxLayout(pnl_top, javax.swing.BoxLayout.Y_AXIS));

        pnl_filter.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_filter.setMinimumSize(new java.awt.Dimension(92, 50));
        pnl_filter.setLayout(new javax.swing.BoxLayout(pnl_filter, javax.swing.BoxLayout.X_AXIS));

        txt_filter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_filter.setText("Tìm theo sản phẩm");
        txt_filter.setToolTipText("Tìm theo sản phẩm");
        txt_filter.setFocusCycleRoot(true);
        txt_filter.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        txt_filter.setPreferredSize(new java.awt.Dimension(73, 50));
        pnl_filter.add(txt_filter);

        jButton1.setText("jButton1");
        jButton1.setMaximumSize(new java.awt.Dimension(75, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(75, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 50));
        pnl_filter.add(jButton1);

        pnl_top.add(pnl_filter);

        pnl_advance.setLayout(new java.awt.GridLayout(1, 5, 5, 0));

        jRadioButton2.setText("Tính năng");
        jRadioButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnl_advance.add(jRadioButton2);

        jRadioButton1.setText("Tính năng");
        jRadioButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnl_advance.add(jRadioButton1);

        jRadioButton3.setText("Tính năng");
        jRadioButton3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnl_advance.add(jRadioButton3);

        jRadioButton4.setText("Tính năng");
        jRadioButton4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnl_advance.add(jRadioButton4);

        jRadioButton5.setText("Tính năng");
        jRadioButton5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnl_advance.add(jRadioButton5);

        pnl_top.add(pnl_advance);

        getContentPane().add(pnl_top, java.awt.BorderLayout.NORTH);

        pnl_center.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản phẩm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));
        pnl_center.setEnabled(false);
        pnl_center.setFocusable(false);
        pnl_center.setMinimumSize(new java.awt.Dimension(0, 500));
        pnl_center.setPreferredSize(new java.awt.Dimension(1000, 500));
        pnl_center.setLayout(new java.awt.BorderLayout());

        scr_table.setAutoscrolls(true);

        tbl_dsnv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Nhà Sản Xuất", "Phân Loại", "SL", "Giá nhập", "Giá bán", "TG Bảo hành"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_dsnv.setGridColor(new java.awt.Color(153, 153, 153));
        tbl_dsnv.setRowHeight(30);
        tbl_dsnv.setShowGrid(true);
        tbl_dsnv.setShowVerticalLines(false);
        scr_table.setViewportView(tbl_dsnv);

        pnl_center.add(scr_table, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnl_center, java.awt.BorderLayout.CENTER);

        pnl_bottom.setPreferredSize(new java.awt.Dimension(1000, 50));
        pnl_bottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btn_add.setText("Thêm sản phẩm");
        btn_add.setPreferredSize(new java.awt.Dimension(200, 40));
        pnl_bottom.add(btn_add);

        getContentPane().add(pnl_bottom, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        FlatDarculaLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_QuanLiSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JPanel pnl_advance;
    private javax.swing.JPanel pnl_bottom;
    private javax.swing.JPanel pnl_center;
    private javax.swing.JPanel pnl_filter;
    private javax.swing.JPanel pnl_top;
    private javax.swing.JScrollPane scr_table;
    private javax.swing.JTable tbl_dsnv;
    private javax.swing.JTextField txt_filter;
    // End of variables declaration//GEN-END:variables
}
