/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author macbookk
 */
public class GUI_QuanLyNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form GUI_QuanLyNhanVien
     */
    public GUI_QuanLyNhanVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_ttNhanVien = new javax.swing.JPanel();
        pnl_control = new javax.swing.JPanel();
        pnl_dsNhanVien = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        tbl_dsNhanVien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Nhân Viên");
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setSize(new java.awt.Dimension(1000, 700));

        pnl_ttNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"));
        pnl_ttNhanVien.setPreferredSize(new java.awt.Dimension(350, 400));

        javax.swing.GroupLayout pnl_ttNhanVienLayout = new javax.swing.GroupLayout(pnl_ttNhanVien);
        pnl_ttNhanVien.setLayout(pnl_ttNhanVienLayout);
        pnl_ttNhanVienLayout.setHorizontalGroup(
            pnl_ttNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        pnl_ttNhanVienLayout.setVerticalGroup(
            pnl_ttNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_ttNhanVien, java.awt.BorderLayout.LINE_END);

        pnl_control.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnl_control.setPreferredSize(new java.awt.Dimension(550, 70));

        javax.swing.GroupLayout pnl_controlLayout = new javax.swing.GroupLayout(pnl_control);
        pnl_control.setLayout(pnl_controlLayout);
        pnl_controlLayout.setHorizontalGroup(
            pnl_controlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 833, Short.MAX_VALUE)
        );
        pnl_controlLayout.setVerticalGroup(
            pnl_controlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_control, java.awt.BorderLayout.SOUTH);
        pnl_control.getAccessibleContext().setAccessibleDescription("");
        pnl_control.getAccessibleContext().setAccessibleParent(this);

        pnl_dsNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách nhân viên"));
        pnl_dsNhanVien.setPreferredSize(new java.awt.Dimension(500, 341));
        pnl_dsNhanVien.setLayout(new javax.swing.BoxLayout(pnl_dsNhanVien, javax.swing.BoxLayout.LINE_AXIS));

        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tbl_dsNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Họ tên", "Email", "Số điện thoại", "Chức danh", "Năm sinh"
            }
        ));
        scrollPane.setViewportView(tbl_dsNhanVien);

        pnl_dsNhanVien.add(scrollPane);

        getContentPane().add(pnl_dsNhanVien, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_QuanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnl_control;
    private javax.swing.JPanel pnl_dsNhanVien;
    private javax.swing.JPanel pnl_ttNhanVien;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tbl_dsNhanVien;
    // End of variables declaration//GEN-END:variables
}
