/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.KhachHang_bus;
import java.util.ArrayList;
import javax.swing.JTable;

import javax.swing.table.DefaultTableModel;
import model.connguoi.KhachHang;

/**
 *
 * @author macbookk
 */
public class Panel_QuanLyKhachHang extends javax.swing.JPanel {
    private KhachHang_bus KH_bus = new KhachHang_bus();
    private ArrayList<KhachHang> listKH = new ArrayList<KhachHang>();
    private DefaultTableModel model_dsKhachHang;
    /**
     * Creates new form Panel_QuanLyKhachHang
     */
    public Panel_QuanLyKhachHang() {
        String col[] = {"Mã khách hàng","Họ tên","Điểm thành viên","Số điện thoại","Mã số thuế","Địa chỉ","Năm sinh","Giới tính","Email"};
        model_dsKhachHang= new DefaultTableModel(col,0);
        
        listKH = KH_bus.getAllKhachHang();
        try{
            renderListToTable(listKH);
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
        initComponents();
        tbl_dsKhachHang.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbl_dsKhachHang.getColumnModel().getColumn(0).setPreferredWidth(100);
        tbl_dsKhachHang.getColumnModel().getColumn(1).setPreferredWidth(200);
        tbl_dsKhachHang.getColumnModel().getColumn(2).setPreferredWidth(100);
        tbl_dsKhachHang.getColumnModel().getColumn(3).setPreferredWidth(100);
        tbl_dsKhachHang.getColumnModel().getColumn(4).setPreferredWidth(100);
        tbl_dsKhachHang.getColumnModel().getColumn(5).setPreferredWidth(200);
        tbl_dsKhachHang.getColumnModel().getColumn(6).setPreferredWidth(100);
        tbl_dsKhachHang.getColumnModel().getColumn(7).setPreferredWidth(100);
        tbl_dsKhachHang.getColumnModel().getColumn(8).setPreferredWidth(200);
    }
    
     public void renderListToTable(ArrayList<KhachHang> listNV) {
        model_dsKhachHang.setRowCount(0);
        for(KhachHang kh:listKH){
            String gioiTinh="";
            if(kh.isGioiTinh()){
                gioiTinh="Nam";
            }else{
                gioiTinh="Nữ";
            }
           model_dsKhachHang.addRow(new Object[] {kh.getMaKH(),kh.getHoTen(),kh.getDiemThanhVien(),kh.getSoDT(),kh.getMaSoThue(),kh.getDiaChi(),kh.getNamSinh(),gioiTinh,kh.getEmail()});
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        pnl_ttKhachHang = new javax.swing.JPanel();
        pnl_avata = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_ttKH = new javax.swing.JPanel();
        pnl_maKH = new javax.swing.JPanel();
        lbl_maKH = new javax.swing.JLabel();
        txt_maKH = new javax.swing.JTextField();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 32767));
        pnl_tenKH = new javax.swing.JPanel();
        lbl_tenKH = new javax.swing.JLabel();
        txt_tenKH = new javax.swing.JTextField();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 32767));
        pnl_hangThanhVien = new javax.swing.JPanel();
        lbl_hangThanhVien = new javax.swing.JLabel();
        txt_hangThanhVien = new javax.swing.JTextField();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 32767));
        pnl_soDT = new javax.swing.JPanel();
        lbl_soDT = new javax.swing.JLabel();
        txt_soDT = new javax.swing.JTextField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 32767));
        pnl_maSoThue = new javax.swing.JPanel();
        lbl_maSoThue = new javax.swing.JLabel();
        txt_maSoThue = new javax.swing.JTextField();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 32767));
        pnl_email = new javax.swing.JPanel();
        lbl_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 32767));
        pnl_namSinh = new javax.swing.JPanel();
        lbl_namSinh = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(3, 0));
        lbl_gioiTinh = new javax.swing.JLabel();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(10, 0));
        cmb_gioiTinh = new javax.swing.JComboBox<>();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 32767));
        pnl_capNhat = new javax.swing.JPanel();
        btn_capNhatKH = new javax.swing.JButton();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 32767));
        pnl_dsKhachHang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_dsKhachHang = new javax.swing.JTable();
        pnl_control = new javax.swing.JPanel();
        pnl_timKiem = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(3, 0), new java.awt.Dimension(32767, 0));
        btn_timKiem = new javax.swing.JButton();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(3, 0), new java.awt.Dimension(32767, 0));
        txt_timKiem = new javax.swing.JTextField();
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(3, 0), new java.awt.Dimension(32767, 0));
        jSeparator1 = new javax.swing.JSeparator();
        pnl_controlright = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btn_xoaKH = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btn_themKH = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        jMenu1.setText("jMenu1");

        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(new java.awt.BorderLayout());

        pnl_ttKhachHang.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(65, 165, 238))); // NOI18N
        pnl_ttKhachHang.setPreferredSize(new java.awt.Dimension(400, 300));
        pnl_ttKhachHang.setLayout(new java.awt.BorderLayout());

        pnl_avata.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/quanlynhanvien/user-4.png"))); // NOI18N
        pnl_avata.add(jLabel1, java.awt.BorderLayout.CENTER);

        pnl_ttKhachHang.add(pnl_avata, java.awt.BorderLayout.CENTER);

        pnl_ttKH.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnl_ttKH.setPreferredSize(new java.awt.Dimension(338, 350));
        pnl_ttKH.setLayout(new javax.swing.BoxLayout(pnl_ttKH, javax.swing.BoxLayout.Y_AXIS));

        pnl_maKH.setPreferredSize(new java.awt.Dimension(180, 30));
        pnl_maKH.setLayout(new javax.swing.BoxLayout(pnl_maKH, javax.swing.BoxLayout.LINE_AXIS));

        lbl_maKH.setForeground(new java.awt.Color(102, 102, 102));
        lbl_maKH.setText("Mã khách hàng:");
        lbl_maKH.setPreferredSize(new java.awt.Dimension(110, 18));
        pnl_maKH.add(lbl_maKH);

        txt_maKH.setMinimumSize(new java.awt.Dimension(250, 30));
        txt_maKH.setPreferredSize(new java.awt.Dimension(250, 30));
        txt_maKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maKHActionPerformed(evt);
            }
        });
        pnl_maKH.add(txt_maKH);

        pnl_ttKH.add(pnl_maKH);

        filler8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        pnl_ttKH.add(filler8);

        pnl_tenKH.setMinimumSize(new java.awt.Dimension(65, 30));
        pnl_tenKH.setPreferredSize(new java.awt.Dimension(180, 30));
        pnl_tenKH.setLayout(new javax.swing.BoxLayout(pnl_tenKH, javax.swing.BoxLayout.LINE_AXIS));

        lbl_tenKH.setForeground(new java.awt.Color(102, 102, 102));
        lbl_tenKH.setText("Tên khách hàng: ");
        lbl_tenKH.setPreferredSize(new java.awt.Dimension(110, 18));
        pnl_tenKH.add(lbl_tenKH);

        txt_tenKH.setMinimumSize(new java.awt.Dimension(250, 30));
        txt_tenKH.setPreferredSize(new java.awt.Dimension(250, 30));
        pnl_tenKH.add(txt_tenKH);

        pnl_ttKH.add(pnl_tenKH);

        filler7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        pnl_ttKH.add(filler7);

        pnl_hangThanhVien.setPreferredSize(new java.awt.Dimension(180, 30));
        pnl_hangThanhVien.setLayout(new javax.swing.BoxLayout(pnl_hangThanhVien, javax.swing.BoxLayout.LINE_AXIS));

        lbl_hangThanhVien.setForeground(new java.awt.Color(102, 102, 102));
        lbl_hangThanhVien.setText("Hạng thành viên: ");
        lbl_hangThanhVien.setPreferredSize(new java.awt.Dimension(110, 18));
        pnl_hangThanhVien.add(lbl_hangThanhVien);

        txt_hangThanhVien.setMinimumSize(new java.awt.Dimension(250, 30));
        txt_hangThanhVien.setPreferredSize(new java.awt.Dimension(250, 30));
        txt_hangThanhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hangThanhVienActionPerformed(evt);
            }
        });
        pnl_hangThanhVien.add(txt_hangThanhVien);

        pnl_ttKH.add(pnl_hangThanhVien);

        filler6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        pnl_ttKH.add(filler6);

        pnl_soDT.setPreferredSize(new java.awt.Dimension(180, 30));
        pnl_soDT.setLayout(new javax.swing.BoxLayout(pnl_soDT, javax.swing.BoxLayout.LINE_AXIS));

        lbl_soDT.setForeground(new java.awt.Color(102, 102, 102));
        lbl_soDT.setText("Số điện thoại:");
        lbl_soDT.setPreferredSize(new java.awt.Dimension(110, 18));
        pnl_soDT.add(lbl_soDT);

        txt_soDT.setMinimumSize(new java.awt.Dimension(250, 30));
        txt_soDT.setPreferredSize(new java.awt.Dimension(250, 30));
        txt_soDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soDTActionPerformed(evt);
            }
        });
        pnl_soDT.add(txt_soDT);

        pnl_ttKH.add(pnl_soDT);

        filler5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        pnl_ttKH.add(filler5);

        pnl_maSoThue.setPreferredSize(new java.awt.Dimension(180, 30));
        pnl_maSoThue.setLayout(new javax.swing.BoxLayout(pnl_maSoThue, javax.swing.BoxLayout.LINE_AXIS));

        lbl_maSoThue.setForeground(new java.awt.Color(102, 102, 102));
        lbl_maSoThue.setText("Mã số thuế: ");
        lbl_maSoThue.setPreferredSize(new java.awt.Dimension(110, 18));
        pnl_maSoThue.add(lbl_maSoThue);

        txt_maSoThue.setMinimumSize(new java.awt.Dimension(250, 30));
        txt_maSoThue.setPreferredSize(new java.awt.Dimension(250, 30));
        pnl_maSoThue.add(txt_maSoThue);

        pnl_ttKH.add(pnl_maSoThue);

        filler9.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        pnl_ttKH.add(filler9);

        pnl_email.setPreferredSize(new java.awt.Dimension(180, 30));
        pnl_email.setLayout(new javax.swing.BoxLayout(pnl_email, javax.swing.BoxLayout.LINE_AXIS));

        lbl_email.setForeground(new java.awt.Color(102, 102, 102));
        lbl_email.setText("Email: ");
        lbl_email.setPreferredSize(new java.awt.Dimension(110, 18));
        pnl_email.add(lbl_email);

        txt_email.setMinimumSize(new java.awt.Dimension(250, 30));
        txt_email.setPreferredSize(new java.awt.Dimension(250, 30));
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        pnl_email.add(txt_email);

        pnl_ttKH.add(pnl_email);

        filler11.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        pnl_ttKH.add(filler11);

        pnl_namSinh.setPreferredSize(new java.awt.Dimension(180, 30));
        pnl_namSinh.setLayout(new javax.swing.BoxLayout(pnl_namSinh, javax.swing.BoxLayout.LINE_AXIS));

        lbl_namSinh.setForeground(new java.awt.Color(102, 102, 102));
        lbl_namSinh.setText("Năm sinh: ");
        lbl_namSinh.setPreferredSize(new java.awt.Dimension(110, 18));
        pnl_namSinh.add(lbl_namSinh);

        jDateChooser2.setMaximumSize(new java.awt.Dimension(100000, 2147483647));
        jDateChooser2.setMinimumSize(new java.awt.Dimension(100, 23));
        jDateChooser2.setPreferredSize(new java.awt.Dimension(55, 30));
        pnl_namSinh.add(jDateChooser2);
        pnl_namSinh.add(filler16);

        lbl_gioiTinh.setForeground(new java.awt.Color(102, 102, 102));
        lbl_gioiTinh.setText("Giới tính:");
        pnl_namSinh.add(lbl_gioiTinh);
        pnl_namSinh.add(filler15);

        cmb_gioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cmb_gioiTinh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmb_gioiTinh.setPreferredSize(new java.awt.Dimension(65, 30));
        pnl_namSinh.add(cmb_gioiTinh);

        pnl_ttKH.add(pnl_namSinh);

        filler10.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        pnl_ttKH.add(filler10);

        pnl_capNhat.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        pnl_capNhat.setMinimumSize(new java.awt.Dimension(65, 30));
        pnl_capNhat.setPreferredSize(new java.awt.Dimension(180, 50));
        pnl_capNhat.setLayout(new javax.swing.BoxLayout(pnl_capNhat, javax.swing.BoxLayout.LINE_AXIS));

        btn_capNhatKH.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btn_capNhatKH.setText("Cập Nhật Thông Tin");
        btn_capNhatKH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_capNhatKH.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        btn_capNhatKH.setPreferredSize(new java.awt.Dimension(190, 50));
        pnl_capNhat.add(btn_capNhatKH);

        pnl_ttKH.add(pnl_capNhat);

        filler12.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        pnl_ttKH.add(filler12);

        pnl_ttKhachHang.add(pnl_ttKH, java.awt.BorderLayout.SOUTH);

        add(pnl_ttKhachHang, java.awt.BorderLayout.EAST);

        pnl_dsKhachHang.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Danh sách khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(65, 165, 238))); // NOI18N
        pnl_dsKhachHang.setPreferredSize(new java.awt.Dimension(600, 370));
        pnl_dsKhachHang.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tbl_dsKhachHang.setModel(model_dsKhachHang);
        jScrollPane1.setViewportView(tbl_dsKhachHang);

        pnl_dsKhachHang.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(pnl_dsKhachHang, java.awt.BorderLayout.CENTER);

        pnl_control.setPreferredSize(new java.awt.Dimension(726, 70));
        pnl_control.setLayout(new javax.swing.BoxLayout(pnl_control, javax.swing.BoxLayout.LINE_AXIS));

        pnl_timKiem.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        pnl_timKiem.setPreferredSize(new java.awt.Dimension(500, 50));
        pnl_timKiem.setLayout(new javax.swing.BoxLayout(pnl_timKiem, javax.swing.BoxLayout.LINE_AXIS));
        pnl_timKiem.add(filler4);

        btn_timKiem.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btn_timKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banhang/cartSearch.png"))); // NOI18N
        btn_timKiem.setText("Tìm kiếm");
        btn_timKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_timKiem.setMaximumSize(new java.awt.Dimension(151, 340));
        btn_timKiem.setPreferredSize(new java.awt.Dimension(130, 40));
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });
        pnl_timKiem.add(btn_timKiem);
        pnl_timKiem.add(filler13);

        txt_timKiem.setPreferredSize(new java.awt.Dimension(300, 40));
        pnl_timKiem.add(txt_timKiem);
        pnl_timKiem.add(filler14);

        pnl_control.add(pnl_timKiem);

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        pnl_control.add(jSeparator1);

        pnl_controlright.setMaximumSize(new java.awt.Dimension(338, 50));
        pnl_controlright.setMinimumSize(new java.awt.Dimension(338, 24));
        pnl_controlright.setPreferredSize(new java.awt.Dimension(400, 100));
        pnl_controlright.setLayout(new javax.swing.BoxLayout(pnl_controlright, javax.swing.BoxLayout.LINE_AXIS));
        pnl_controlright.add(filler2);

        btn_xoaKH.setBackground(new java.awt.Color(255, 153, 153));
        btn_xoaKH.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btn_xoaKH.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoaKH.setText("Xoá Khách Hàng");
        btn_xoaKH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_xoaKH.setMaximumSize(new java.awt.Dimension(150, 50));
        btn_xoaKH.setPreferredSize(new java.awt.Dimension(190, 50));
        pnl_controlright.add(btn_xoaKH);
        pnl_controlright.add(filler1);

        btn_themKH.setBackground(new java.awt.Color(65, 165, 238));
        btn_themKH.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btn_themKH.setForeground(new java.awt.Color(255, 255, 255));
        btn_themKH.setText("Thêm Khách Hàng");
        btn_themKH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_themKH.setMaximumSize(new java.awt.Dimension(150, 50));
        btn_themKH.setPreferredSize(new java.awt.Dimension(190, 50));
        pnl_controlright.add(btn_themKH);
        pnl_controlright.add(filler3);

        pnl_control.add(pnl_controlright);

        add(pnl_control, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_maKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maKHActionPerformed

    private void txt_hangThanhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hangThanhVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hangThanhVienActionPerformed

    private void txt_soDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soDTActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        
    }//GEN-LAST:event_btn_timKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capNhatKH;
    private javax.swing.JButton btn_themKH;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_xoaKH;
    private javax.swing.JComboBox<String> cmb_gioiTinh;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_gioiTinh;
    private javax.swing.JLabel lbl_hangThanhVien;
    private javax.swing.JLabel lbl_maKH;
    private javax.swing.JLabel lbl_maSoThue;
    private javax.swing.JLabel lbl_namSinh;
    private javax.swing.JLabel lbl_soDT;
    private javax.swing.JLabel lbl_tenKH;
    private javax.swing.JPanel pnl_avata;
    private javax.swing.JPanel pnl_capNhat;
    private javax.swing.JPanel pnl_control;
    private javax.swing.JPanel pnl_controlright;
    private javax.swing.JPanel pnl_dsKhachHang;
    private javax.swing.JPanel pnl_email;
    private javax.swing.JPanel pnl_hangThanhVien;
    private javax.swing.JPanel pnl_maKH;
    private javax.swing.JPanel pnl_maSoThue;
    private javax.swing.JPanel pnl_namSinh;
    private javax.swing.JPanel pnl_soDT;
    private javax.swing.JPanel pnl_tenKH;
    private javax.swing.JPanel pnl_timKiem;
    private javax.swing.JPanel pnl_ttKH;
    private javax.swing.JPanel pnl_ttKhachHang;
    private javax.swing.JTable tbl_dsKhachHang;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_hangThanhVien;
    private javax.swing.JTextField txt_maKH;
    private javax.swing.JTextField txt_maSoThue;
    private javax.swing.JTextField txt_soDT;
    private javax.swing.JTextField txt_tenKH;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables
}
