/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.sanpham.SanPham;
import model.sanpham.ThuongHieu;

/**
 *
 * @author nxnam
 */
public class Panel_QuanLySanPham extends javax.swing.JPanel {

    private DefaultTableModel tbl_ModelProduct;
    private String[] str_TenCot = new String[]{"Mã sản phẩm", "Tên sản phẩm", "Loại sản phẩm", "Thương hiệu", "Cấu hình", "Giá cả", "Số lượng"};

    /**
     * Creates new form Panel_QuanLySanPham
     */
    public Panel_QuanLySanPham() {
        tbl_ModelProduct = new DefaultTableModel(str_TenCot, 0);
        initComponents();
        initTableModel();
    }
    
    private void initTableModel() {
        ArrayList<SanPham> list = new ArrayList<>();
        try {
            list.add(new SanPham("sp1", "chuot1", 200, 10, SanPham.CHUOT, 8, new ThuongHieu("th1", "Itel", "Trung"), 5, "DPI:3000"));
            list.add(new SanPham("sp2", "chuot2", 200, 10, SanPham.CHUOT, 8, new ThuongHieu("th1", "Itel", "Trung"), 5, "DPI:3000"));
            list.add(new SanPham("sp3", "chuot3", 200, 10, SanPham.CHUOT, 8, new ThuongHieu("th1", "Itel", "Trung"), 5, "DPI:3000"));
            renderProductTable(list);
        } catch(Exception e) {
        
        }
    }
    
    private void renderProductTable(ArrayList<SanPham> list) {
        tbl_ModelProduct.setRowCount(0);
        for (SanPham sp : list) {
            Object[] row = new Object[]{sp.getMaSP(), sp.getTenSP(), sp.getTenLoai(), sp.getThuongHieu().toString(), 0, sp.getGiaBan()};
            tbl_ModelProduct.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        pnl_ThongTin = new javax.swing.JPanel();
        pnl_head_TT = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        pnl_body_TT = new javax.swing.JPanel();
        pnl_Tensp = new javax.swing.JPanel();
        lbl_Tensp = new javax.swing.JLabel();
        txt_Tensp = new javax.swing.JTextField();
        pnl_SoLuong = new javax.swing.JPanel();
        lbl_SoLuong = new javax.swing.JLabel();
        txt_SoLuong = new javax.swing.JTextField();
        pnl_GiaBan = new javax.swing.JPanel();
        lbl_GiaBan = new javax.swing.JLabel();
        txt_GiaBan = new javax.swing.JTextField();
        pnl_Loaisp = new javax.swing.JPanel();
        lbl_Loaisp = new javax.swing.JLabel();
        cmp_Loaisp = new javax.swing.JComboBox<>();
        pnl_ThuongHieu = new javax.swing.JPanel();
        lbl_ThuongHieu = new javax.swing.JLabel();
        cmb_ThuongHieu = new javax.swing.JComboBox<>();
        pnl_CauHinh = new javax.swing.JPanel();
        lbl_CauHinh = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtarea_CauHinh = new javax.swing.JTextArea();
        pnl_NutQuanLy = new javax.swing.JPanel();
        btn_Them = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        pnl_TimKiem = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(40, 32767));
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(40, 32767));
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        pnl_DanhSach = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Products = new javax.swing.JTable();

        jTextField2.setText("jTextField2");

        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(new java.awt.BorderLayout());

        pnl_ThongTin.setBackground(new java.awt.Color(255, 255, 255));
        pnl_ThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(65, 165, 238))); // NOI18N
        pnl_ThongTin.setPreferredSize(new java.awt.Dimension(320, 600));
        pnl_ThongTin.setLayout(new java.awt.BorderLayout());

        pnl_head_TT.setBackground(new java.awt.Color(255, 255, 255));
        pnl_head_TT.setLayout(new java.awt.BorderLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/QLhanghoa/img_Sanpham (200px).png"))); // NOI18N
        jLabel13.setToolTipText("");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl_head_TT.add(jLabel13, java.awt.BorderLayout.CENTER);
        pnl_head_TT.add(filler1, java.awt.BorderLayout.PAGE_END);

        pnl_ThongTin.add(pnl_head_TT, java.awt.BorderLayout.NORTH);

        pnl_body_TT.setBackground(new java.awt.Color(255, 255, 255));
        pnl_body_TT.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnl_body_TT.setPreferredSize(new java.awt.Dimension(140, 20));
        pnl_body_TT.setLayout(new javax.swing.BoxLayout(pnl_body_TT, javax.swing.BoxLayout.Y_AXIS));

        pnl_Tensp.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Tensp.setPreferredSize(new java.awt.Dimension(0, 30));
        pnl_Tensp.setLayout(new javax.swing.BoxLayout(pnl_Tensp, javax.swing.BoxLayout.LINE_AXIS));

        lbl_Tensp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_Tensp.setText("Tên sản phẩm:");
        lbl_Tensp.setPreferredSize(new java.awt.Dimension(120, 0));
        pnl_Tensp.add(lbl_Tensp);

        txt_Tensp.setMaximumSize(new java.awt.Dimension(1000, 500));
        txt_Tensp.setMinimumSize(new java.awt.Dimension(140, 16));
        txt_Tensp.setPreferredSize(new java.awt.Dimension(160, 24));
        txt_Tensp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenspActionPerformed(evt);
            }
        });
        pnl_Tensp.add(txt_Tensp);

        pnl_body_TT.add(pnl_Tensp);

        pnl_SoLuong.setBackground(new java.awt.Color(255, 255, 255));
        pnl_SoLuong.setPreferredSize(new java.awt.Dimension(0, 30));
        pnl_SoLuong.setLayout(new javax.swing.BoxLayout(pnl_SoLuong, javax.swing.BoxLayout.LINE_AXIS));

        lbl_SoLuong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_SoLuong.setText("Số lượng:");
        lbl_SoLuong.setPreferredSize(new java.awt.Dimension(120, 0));
        pnl_SoLuong.add(lbl_SoLuong);

        txt_SoLuong.setMaximumSize(new java.awt.Dimension(1000, 500));
        txt_SoLuong.setMinimumSize(new java.awt.Dimension(140, 16));
        txt_SoLuong.setPreferredSize(new java.awt.Dimension(160, 24));
        pnl_SoLuong.add(txt_SoLuong);

        pnl_body_TT.add(pnl_SoLuong);

        pnl_GiaBan.setBackground(new java.awt.Color(255, 255, 255));
        pnl_GiaBan.setPreferredSize(new java.awt.Dimension(0, 30));
        pnl_GiaBan.setLayout(new javax.swing.BoxLayout(pnl_GiaBan, javax.swing.BoxLayout.LINE_AXIS));

        lbl_GiaBan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_GiaBan.setText("Giá bán:");
        lbl_GiaBan.setPreferredSize(new java.awt.Dimension(120, 0));
        pnl_GiaBan.add(lbl_GiaBan);

        txt_GiaBan.setMaximumSize(new java.awt.Dimension(1000, 500));
        txt_GiaBan.setMinimumSize(new java.awt.Dimension(140, 16));
        txt_GiaBan.setPreferredSize(new java.awt.Dimension(160, 24));
        pnl_GiaBan.add(txt_GiaBan);

        pnl_body_TT.add(pnl_GiaBan);

        pnl_Loaisp.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Loaisp.setPreferredSize(new java.awt.Dimension(0, 30));
        pnl_Loaisp.setLayout(new javax.swing.BoxLayout(pnl_Loaisp, javax.swing.BoxLayout.LINE_AXIS));

        lbl_Loaisp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_Loaisp.setText("Loại sản phẩm:");
        lbl_Loaisp.setPreferredSize(new java.awt.Dimension(120, 0));
        pnl_Loaisp.add(lbl_Loaisp);

        cmp_Loaisp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmp_Loaisp.setMaximumSize(new java.awt.Dimension(1000, 500));
        cmp_Loaisp.setMinimumSize(new java.awt.Dimension(140, 16));
        cmp_Loaisp.setPreferredSize(new java.awt.Dimension(160, 24));
        pnl_Loaisp.add(cmp_Loaisp);

        pnl_body_TT.add(pnl_Loaisp);

        pnl_ThuongHieu.setBackground(new java.awt.Color(255, 255, 255));
        pnl_ThuongHieu.setPreferredSize(new java.awt.Dimension(0, 30));
        pnl_ThuongHieu.setLayout(new javax.swing.BoxLayout(pnl_ThuongHieu, javax.swing.BoxLayout.LINE_AXIS));

        lbl_ThuongHieu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ThuongHieu.setText("Thương hiêu:");
        lbl_ThuongHieu.setPreferredSize(new java.awt.Dimension(120, 0));
        pnl_ThuongHieu.add(lbl_ThuongHieu);

        cmb_ThuongHieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_ThuongHieu.setMaximumSize(new java.awt.Dimension(1000, 500));
        cmb_ThuongHieu.setMinimumSize(new java.awt.Dimension(140, 16));
        cmb_ThuongHieu.setPreferredSize(new java.awt.Dimension(160, 24));
        pnl_ThuongHieu.add(cmb_ThuongHieu);

        pnl_body_TT.add(pnl_ThuongHieu);

        pnl_CauHinh.setBackground(new java.awt.Color(255, 255, 255));
        pnl_CauHinh.setPreferredSize(new java.awt.Dimension(0, 30));
        pnl_CauHinh.setLayout(new javax.swing.BoxLayout(pnl_CauHinh, javax.swing.BoxLayout.LINE_AXIS));

        lbl_CauHinh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_CauHinh.setText("Cấu hình:");
        lbl_CauHinh.setPreferredSize(new java.awt.Dimension(138, 138));
        pnl_CauHinh.add(lbl_CauHinh);

        txtarea_CauHinh.setColumns(20);
        txtarea_CauHinh.setRows(5);
        txtarea_CauHinh.setPreferredSize(new java.awt.Dimension(200, 24));
        jScrollPane2.setViewportView(txtarea_CauHinh);

        pnl_CauHinh.add(jScrollPane2);

        pnl_body_TT.add(pnl_CauHinh);

        pnl_ThongTin.add(pnl_body_TT, java.awt.BorderLayout.CENTER);

        pnl_NutQuanLy.setBackground(new java.awt.Color(255, 255, 255));
        pnl_NutQuanLy.setLayout(new java.awt.GridLayout());

        btn_Them.setText("Thêm");
        btn_Them.setMaximumSize(new java.awt.Dimension(80, 40));
        btn_Them.setPreferredSize(new java.awt.Dimension(80, 32));
        pnl_NutQuanLy.add(btn_Them);

        btn_Xoa.setText("Xóa");
        btn_Xoa.setMaximumSize(new java.awt.Dimension(80, 40));
        btn_Xoa.setPreferredSize(new java.awt.Dimension(80, 40));
        pnl_NutQuanLy.add(btn_Xoa);

        btn_Sua.setText("Sửa");
        btn_Sua.setMaximumSize(new java.awt.Dimension(80, 40));
        btn_Sua.setPreferredSize(new java.awt.Dimension(80, 40));
        pnl_NutQuanLy.add(btn_Sua);

        pnl_ThongTin.add(pnl_NutQuanLy, java.awt.BorderLayout.SOUTH);

        add(pnl_ThongTin, java.awt.BorderLayout.EAST);

        pnl_TimKiem.setBackground(new java.awt.Color(255, 255, 255));
        pnl_TimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(65, 165, 238))); // NOI18N
        pnl_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnl_TimKiem.setPreferredSize(new java.awt.Dimension(0, 150));
        pnl_TimKiem.setLayout(new javax.swing.BoxLayout(pnl_TimKiem, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 50));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tên sản phẩm:");
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 0));
        jPanel1.add(jLabel1);

        jTextField1.setPreferredSize(new java.awt.Dimension(650, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);

        jPanel7.setMaximumSize(new java.awt.Dimension(4001111, 2147483647));
        jPanel7.setMinimumSize(new java.awt.Dimension(1000, 50));
        jPanel7.setPreferredSize(new java.awt.Dimension(140, 50));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banhang/cartSearch.png"))); // NOI18N
        jButton1.setText("Tìm Kiếm");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setMaximumSize(new java.awt.Dimension(400, 1000));
        jButton1.setMinimumSize(new java.awt.Dimension(400, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7);

        pnl_TimKiem.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Cấu hình:");
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 0));
        jPanel3.add(jLabel2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1);

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));
        jPanel5.add(filler6);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Loại sản phẩm:");
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 0));
        jPanel5.add(jLabel3);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(jComboBox1);

        jPanel4.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));
        jPanel6.add(filler7);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Thương hiệu:");
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 0));
        jPanel6.add(jLabel4);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel6.add(jComboBox2);

        jPanel4.add(jPanel6);

        jPanel2.add(jPanel4);

        pnl_TimKiem.add(jPanel2);
        pnl_TimKiem.add(filler12);

        add(pnl_TimKiem, java.awt.BorderLayout.NORTH);

        pnl_DanhSach.setBackground(new java.awt.Color(255, 255, 255));
        pnl_DanhSach.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(65, 165, 238))); // NOI18N
        pnl_DanhSach.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        tbl_Products.setModel(tbl_ModelProduct);
        tbl_Products.setRowHeight(30);
        jScrollPane3.setViewportView(tbl_Products);

        pnl_DanhSach.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        add(pnl_DanhSach, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_TenspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenspActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JComboBox<String> cmb_ThuongHieu;
    private javax.swing.JComboBox<String> cmp_Loaisp;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl_CauHinh;
    private javax.swing.JLabel lbl_GiaBan;
    private javax.swing.JLabel lbl_Loaisp;
    private javax.swing.JLabel lbl_SoLuong;
    private javax.swing.JLabel lbl_Tensp;
    private javax.swing.JLabel lbl_ThuongHieu;
    private javax.swing.JPanel pnl_CauHinh;
    private javax.swing.JPanel pnl_DanhSach;
    private javax.swing.JPanel pnl_GiaBan;
    private javax.swing.JPanel pnl_Loaisp;
    private javax.swing.JPanel pnl_NutQuanLy;
    private javax.swing.JPanel pnl_SoLuong;
    private javax.swing.JPanel pnl_Tensp;
    private javax.swing.JPanel pnl_ThongTin;
    private javax.swing.JPanel pnl_ThuongHieu;
    private javax.swing.JPanel pnl_TimKiem;
    private javax.swing.JPanel pnl_body_TT;
    private javax.swing.JPanel pnl_head_TT;
    private javax.swing.JTable tbl_Products;
    private javax.swing.JTextField txt_GiaBan;
    private javax.swing.JTextField txt_SoLuong;
    private javax.swing.JTextField txt_Tensp;
    private javax.swing.JTextArea txtarea_CauHinh;
    // End of variables declaration//GEN-END:variables

    


}
