/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.SanPham_bus;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.sanpham.SanPham;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;

import org.jfree.chart.plot.PlotOrientation;

import org.jfree.data.category.DefaultCategoryDataset;



/**
 *
 * @author macbookk
 */
public class Panel_ThongKe extends javax.swing.JPanel {

    DefaultTableModel model_dsSanPham;
    private final SanPham_bus sp_bus = new SanPham_bus();

    /**
     * Creates new form Panel_ThongKe
     */
    public Panel_ThongKe() {
        String colname[] = {"Mã sản phẩm", "Tên sản phẩm", "Thương hiệu", "Tổng doanh thu"};
        model_dsSanPham = new DefaultTableModel(colname, 0);
        initComponents();
        ChartPanel chartPanel = new ChartPanel(createLineChart());

        chartPanel.setPreferredSize(new java.awt.Dimension(560, 367));
        pnl_chart.add(chartPanel);
        
       

        alterTable();
        renderListToTable(sp_bus.getAllSanPham());

    }
        private static DefaultCategoryDataset createDataset() {


        DefaultCategoryDataset dataset = new DefaultCategoryDataset();


        dataset.addValue(5.37, "Total", "1");


        dataset.addValue(6.78, "Total", "2");
        dataset.addValue(6.78, "Total", "3");
        dataset.addValue(6.78, "Total", "4");
        dataset.addValue(6.78, "Total", "5");
        dataset.addValue(6.78, "Total", "6");
        dataset.addValue(6.78, "Total", "7");
        dataset.addValue(6.78, "Total", "8");
        dataset.addValue(6.78, "Total", "9");
        dataset.addValue(6.78, "Total", "10");
        dataset.addValue(6.78, "Total", "11");
        dataset.addValue(6.78, "Total", "12");
        
        




        return dataset;


    }


    


    public static JFreeChart createLineChart() {


        JFreeChart lineChart = ChartFactory.createLineChart(


                "BarChart".toUpperCase(),


                "Month", "Total", createDataset(),


                PlotOrientation.VERTICAL, false, false, false);


        return lineChart;


    }

    public void renderListToTable(ArrayList<SanPham> list) {
        model_dsSanPham.setRowCount(0);
        for (SanPham sp : list) {
            String gioiTinh;
            model_dsSanPham.addRow(new Object[]{sp.getMaSP(), sp.getTenSP(), sp.getThuongHieu().getMaTH(), sp.getGiaBan()});
        }

    }

    

    public void alterTable() {
        tbl_sanPham.setRowHeight(80);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_header = new javax.swing.JPanel();
        pnl_img = new javax.swing.JPanel();
        pnl_topItem = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sanPham = new javax.swing.JTable();
        pnl_chart = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(new java.awt.BorderLayout());

        pnl_header.setPreferredSize(new java.awt.Dimension(1000, 300));
        pnl_header.setLayout(new java.awt.BorderLayout());

        pnl_img.setPreferredSize(new java.awt.Dimension(350, 250));

        javax.swing.GroupLayout pnl_imgLayout = new javax.swing.GroupLayout(pnl_img);
        pnl_img.setLayout(pnl_imgLayout);
        pnl_imgLayout.setHorizontalGroup(
            pnl_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        pnl_imgLayout.setVerticalGroup(
            pnl_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pnl_header.add(pnl_img, java.awt.BorderLayout.WEST);

        pnl_topItem.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Top sản phẩm bán chạy trong tháng : ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14), new java.awt.Color(65, 165, 238))); // NOI18N
        pnl_topItem.setLayout(new javax.swing.BoxLayout(pnl_topItem, javax.swing.BoxLayout.Y_AXIS));

        tbl_sanPham.setModel(model_dsSanPham
        );
        jScrollPane1.setViewportView(tbl_sanPham);

        pnl_topItem.add(jScrollPane1);

        pnl_header.add(pnl_topItem, java.awt.BorderLayout.CENTER);

        add(pnl_header, java.awt.BorderLayout.NORTH);

        pnl_chart.setLayout(new java.awt.BorderLayout());
        add(pnl_chart, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl_chart;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_img;
    private javax.swing.JPanel pnl_topItem;
    private javax.swing.JTable tbl_sanPham;
    // End of variables declaration//GEN-END:variables
}
